### model
# model_name_or_path: /mnt/tidal-alsh01/dataset/zeus/hecunjie/models/Qwen/Qwen2.5-7B-Instruct
model_name_or_path: /mnt/tidal-alsh01/dataset/zeus/hecunjie/models/Qwen/Qwen2.5-32B-Instruct
trust_remote_code: true
resize_vocab: true   # required: latent tokens expand vocabulary

### latent thinking
# Auto-adds <latent_0>..<latent_4> to tokenizer, appended as prompt context.
# Think block labels = IGNORE (no SFT loss); only answer + reasoning have loss.
num_latent_thinking_token: 5
reasoning_loss_weight: 1.0  # total_loss = loss_answer + reasoning_loss_weight * loss_reasoning

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
# Use reasoning_train_gsm8k on training server; reasoning_demo for local testing
dataset: reasoning_train_gsm8k
# dataset: reasoning_demo
template: qwen
cutoff_len: 1024
# max_samples: 1000
preprocessing_num_workers: 64
dataloader_num_workers: 64
remove_unused_columns: false  # required: keep reasoning fields for trainer

### output
output_dir: /mnt/tidal-alsh01/dataset/zeus/hecunjie/train_outputs/latent_thinking_gsm8k_32B_0221
logging_steps: 1
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb
run_name: latent_thinking_gsm8k_32B_0221

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 5.0e-6
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
compute_exact_match: true

### eval
eval_dataset: reasoning_test_gsm8k
# eval_dataset: reasoning_demo
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 50